- name: Ensure there are SSH keys for the root user to communicate between nodes
  shell: crm cluster init -y ssh
  args:
    creates: /root/.ssh/id_rsa

- name: Ensure the public SSH keys are available for exchanging SSH key trust between nodes
  shell: cat /root/.ssh/id_rsa.pub
  register: cluster_public_ssh_key

- name: Ensure the public SSH keys are authorized on all nodes, required for crm cluster
  authorized_key:
    user: root
    key: "{{ hostvars[inventory_hostname].cluster_public_ssh_key.stdout }}"
  delegate_to: "{{ item }}"
  loop: "{{ groups['linux'] }}"

- name: enable PermitRootLogin 
  lineinfile: 
    path: /etc/ssh/sshd_config 
    regexp: '^#PermitRootLogin yes(.*)$' 
    line: 'PermitRootLogin yes'

- name: set AuthorizedKeysFile path
  lineinfile: 
    path: /etc/ssh/sshd_config 
    regexp: '^AuthorizedKeysFile(.*)$' 
    line: 'AuthorizedKeysFile      /root/.ssh/authorized_keys'

- name: Restart the sshd daemon
  shell: sudo systemctl restart sshd
